### ISSUE TITLE
[DMS] Add createStripeAccount nonprofit action

### ISSUE THREAD

**Issue by KoolCards** [GTBitsOfGood/gen-soln#103]
Currently, there isn't a way to create a Stripe account for nonprofits who use our website. We need to create a function that does this, so that nonprofits can receive payments. We need to create a connected Stripe account for the nonprofit by redirecting the nonprofit to the Stripe web form (basically we'd redirect the user to a site like [this](https://dashboard.stripe.com/oauth/authorize?response_type=code&client_id=ca_GzSc2LsvquOYz0PviCx3AiSsMorLoN6B&scope=read_write)). 

- [x] Create a new nonprofit action (server/actions/nonprofit.ts) called `createStripeAccount`. You'll likely have to also create a new Stripe object in the nonprofit.ts file (look at server/actions/nonprofit.ts). You'll have to parse the account object that stripe returns for the account number and return this value. [Step 2.1](https://stripe.com/docs/connect/enable-payment-acceptance-guide)
- [x] Create a new nonprofit action (server/actions/nonprofit.ts) called `linkStripeAccount`. This function should accept a Stripe account number as the parameter. [Step 2.2](https://stripe.com/docs/connect/enable-payment-acceptance-guide)

The `linkStripeAccount` function itself should do 2 things.
1. Create an account link using the **connected** account id as the paramter. For now, just have the refresh and redirect url's point to back to the donate page in `config.ts`. 
2. Parse whatever Stripe returns from the account link for the url to redirect the user to.

- [x] Test your functions by calling `createStripeAccount` to get an account number and then calling `linkStripeAccount` for a url. Go to this url in a private browser and ensure that it looks similar to [this](https://dashboard.stripe.com/oauth/authorize?response_type=code&client_id=ca_GzSc2LsvquOYz0PviCx3AiSsMorLoN6B&scope=read_write).

**Comment by ML-Chen** [comment]
For the first subtask, here's what I've written so far. I'm not sure if this is what it is asking for, especially the part about "create a new Standard account with the bank account information".
```
import Stripe from "stripe";

/* eslint-disable-next-line @typescript-eslint/no-non-null-assertion */
const stripe = new Stripe(config.stripe.secret_key!, {
  apiVersion: "2020-03-02"
});

// ...

export async function createStripeAccount() {
  const account = await stripe.accounts.create({
    type: "standard"
  });

  return account.id;
}
```

**Comment by KoolCards** [comment]
Sorry that was remnants from an earlier version of the issue. What you have right now is everything we need for the first subtask, and disregard the bank account info stuff. I updated the zenhub issue to reflect this.

**Comment by ML-Chen** [comment]
How do I get the URL of the donate page to redirect to?
```ts
const defaultNonprofitId = await getDefaultNonprofitId();
config.pages.donate(defaultNonprofitId); // → /donate/64357724
```

but this isn't a valid URL to set as `refresh_url` or `return_url`, probably because it's missing the base URL part of http://localhost:3000. How do I get the base URL?

**Comment by KoolCards** [comment]
Yea for that part, we'd need to modify the config.ts file to set a base url variable passed on an environment variable. I was thinking that could be a separate issue which is why I thought we could just use the donate page path for now. However, it seems like a pretty quick fix. Do you think you can add baseUrl as a field in config.ts that looks for either the DEV_BASE_URL or PROD_BASE_URL environment variable? At then also update the .env.development file with the DEV_BASE_URL=localhost:3000?

**Comment by ML-Chen** [comment]
Is it okay if it looks like this?
![image](https://user-images.githubusercontent.com/6678625/93030380-a22c7480-f5f0-11ea-8f73-d968f59cc6e4.png)

**Comment by PC98** [comment]
Do we need a `baseUrl`, did you test out your code without it? I understand that `/donate/some_id` isn't a full valid URL but in those cases, the function/caller usually just assumes that it has to use the same host. As an example, when you do `fetch("/donate")` the fetch request is sent to the same host with the path `/donate`.

**Comment by ML-Chen** [comment]
Yeah, if we pass a URL without a base URL, Stripe complains that it's an invalid URL.

```ts
  const defaultNonprofitId = await getDefaultNonprofitId();
  const accountLink = await stripe.accountLinks.create({
    account: accountId,
    // Placeholder URLs
    refresh_url: config.pages.donate(defaultNonprofitId),
    return_url: config.pages.donate(defaultNonprofitId),
    type: "account_onboarding"
  });
```

```
StripeInvalidRequestError: Not a valid URL
    at Function.generate (C:\Users\micha\Documents\Git\gen-soln\node_modules\stripe\lib\Error.js:39:16)
    at IncomingMessage.<anonymous> (C:\Users\micha\Documents\Git\gen-soln\node_modules\stripe\lib\StripeResource.js:190:33)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'StripeInvalidRequestError',
  raw: {
    code: 'url_invalid',
    doc_url: 'https://stripe.com/docs/error-codes/url-invalid',
    message: 'Not a valid URL',
    param: 'return_url',
    type: 'invalid_request_error',
    headers: {
      server: 'nginx',
      date: 'Sun, 13 Sep 2020 22:26:49 GMT',
      'content-type': 'application/json',
      'content-length': '211',
      connection: 'keep-alive',
      'access-control-allow-credentials': 'true',
      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
      'access-control-max-age': '300',
      'cache-control': 'no-cache, no-store',
      'request-id': 'req_HVeeYypgSUwX31',
      'stripe-version': '2020-03-02',
      'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
    },
    statusCode: 400,
    requestId: 'req_HVeeYypgSUwX31'
  },
  rawType: 'invalid_request_error',
  code: 'url_invalid',
  doc_url: 'https://stripe.com/docs/error-codes/url-invalid',
  param: 'return_url',
  detail: undefined,
  headers: {
    server: 'nginx',
    date: 'Sun, 13 Sep 2020 22:26:49 GMT',
    'content-type': 'application/json',
    'content-length': '211',
    connection: 'keep-alive',
    'access-control-allow-credentials': 'true',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
    'access-control-max-age': '300',
    'cache-control': 'no-cache, no-store',
    'request-id': 'req_HVeeYypgSUwX31',
    'stripe-version': '2020-03-02',
    'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
  },
  requestId: 'req_HVeeYypgSUwX31',
  statusCode: 400,
  charge: undefined,
  decline_code: undefined,
  payment_intent: undefined,
  payment_method: undefined,
  setup_intent: undefined,
  source: undefined
}
/donate/64357724
StripeInvalidRequestError: Not a valid URL
    at Function.generate (C:\Users\micha\Documents\Git\gen-soln\node_modules\stripe\lib\Error.js:39:16)
    at IncomingMessage.<anonymous> (C:\Users\micha\Documents\Git\gen-soln\node_modules\stripe\lib\StripeResource.js:190:33)
    at Object.onceWrapper (events.js:417:28)
    at IncomingMessage.emit (events.js:323:22)
    at endReadableNT (_stream_readable.js:1204:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21) {
  type: 'StripeInvalidRequestError',
  raw: {
    code: 'url_invalid',
    doc_url: 'https://stripe.com/docs/error-codes/url-invalid',
    message: 'Not a valid URL',
    param: 'return_url',
    type: 'invalid_request_error',
    headers: {
      server: 'nginx',
      date: 'Sun, 13 Sep 2020 22:26:51 GMT',
      'content-type': 'application/json',
      'content-length': '211',
      connection: 'keep-alive',
      'access-control-allow-credentials': 'true',
      'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
      'access-control-allow-origin': '*',
      'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
      'access-control-max-age': '300',
      'cache-control': 'no-cache, no-store',
      'request-id': 'req_jdXRdujOE41jNX',
      'stripe-version': '2020-03-02',
      'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
    },
    statusCode: 400,
    requestId: 'req_jdXRdujOE41jNX'
  },
  rawType: 'invalid_request_error',
  code: 'url_invalid',
  doc_url: 'https://stripe.com/docs/error-codes/url-invalid',
  param: 'return_url',
  detail: undefined,
  headers: {
    server: 'nginx',
    date: 'Sun, 13 Sep 2020 22:26:51 GMT',
    'content-type': 'application/json',
    'content-length': '211',
    connection: 'keep-alive',
    'access-control-allow-credentials': 'true',
    'access-control-allow-methods': 'GET, POST, HEAD, OPTIONS, DELETE',
    'access-control-allow-origin': '*',
    'access-control-expose-headers': 'Request-Id, Stripe-Manage-Version, X-Stripe-External-Auth-Required, X-Stripe-Privileged-Session-Required',
    'access-control-max-age': '300',
    'cache-control': 'no-cache, no-store',
    'request-id': 'req_jdXRdujOE41jNX',
    'stripe-version': '2020-03-02',
    'strict-transport-security': 'max-age=31556926; includeSubDomains; preload'
  },
  requestId: 'req_jdXRdujOE41jNX',
  statusCode: 400,
  charge: undefined,
  decline_code: undefined,
  payment_intent: undefined,
  payment_method: undefined,
  setup_intent: undefined,
  source: undefined
}
```

**Comment by KoolCards** [comment]
yea thats how the stripe redirce url should look michael in response to ur earlier comment
