### ISSUE TITLE
[DMS] Change nonprofitId type to be `Schema.ObjectId`?

### ISSUE THREAD

**Issue by Fattimo** [GTBitsOfGood/gen-soln#123]
See thread linked below. Currently, within /server/models/donation.js, the nonprofitId field has type string, when it should be type Schema.ObjectId.

Can we change this type to also be `Schema.ObjectId`?

_Originally posted by @PC98 in https://github.com/GTBitsOfGood/gen-soln/pull/121#discussion_r486073252_

**Comment by PC98** [comment]
Whoever does this task should also look into if we will need to add a migration script to transfer existing Nonprofits in our DB to use the new schema type.

**Comment by PC98** [comment]
Actually I just realized that in our case, Nonprofit IDs are supposed to be `String`s. So when we create a `ref` to `Nonprofit`, it should be of type `String`. I will close this issue and create a PR to rectify this for our `Event` model.
