### ISSUE TITLE
Add Stripe email receipt notifications

### ISSUE THREAD

**Issue by KoolCards** [GTBitsOfGood/gen-soln#144]
Stripe supports sending email notifications of the transaction receipt, which we want to enable to give people who donate a record of the donation.
- [x] Modify the `createPaymentIntent` function in (server/actions/donations.ts) to accept email as a parameter and update the call to `stripe.paymentIntents.create` to use the email address.
- [x] Refactor all references to `createPaymentIntent` in the frontend to also provide an email address. You'll need to modify an api page, a requests handler function, and a frontend file.

**Comment by ML-Chen** [comment]
I made a test donation with my email address but I haven't gotten any email receipt. Should I have gotten one?
https://github.com/GTBitsOfGood/gen-soln/tree/michael/104-email-notif

**Comment by KoolCards** [comment]
Try it again. I had to update a setting in our Stripe account to enable receipts.

**Comment by ML-Chen** [comment]
I sent another donation and I still haven't received it. https://support.stripe.com/questions/not-receiving-email-sent-from-stripe says "Ensure the email you’re expecting is for a live transaction. Stripe only sends email receipts for payments that are made with your live API key or through your live Dashboard. If you are expecting an email for a test transaction, one will not be sent." Could that be the issue?
