### ISSUE TITLE
[VMS] Add a Next.js page for the `/events/[id]` route

### ISSUE THREAD

**Issue by PC98** [GTBitsOfGood/gen-soln#159]
* Just like we have the `donate/[id].tsx` component, we will have to make a component corresponding to the `/event/[id]` route.
* The UI can just render `null`.
* Be sure to implement the `getStaticPaths` methods which will call the server action that returns all Event IDs.
* Be sure to implement `getStaticProps` which will call a server action to get information about a specific event and return the Event object.
* **Your code will look very similar to `donate/[id].tsx`, however `donate/[id].tsx` is undergoing changes as part of #83**. These are good changes, and we want to incorporate these changes for the `/events/[id]` route as well. If #83 has been closed by the time you start working on this issue, then you can copy code. Otherwise, message me and we will figure out how else to incorporate those changes.
* You should also modify the `pages` object in `config.ts`. We can either change `pages.events` to be a function, like `pages.donate`, or we can add a new field, `pages.event`:
```javascript
donate: (path = "[id]"): string => `/donate/${path}`,
events: "/events",
event: (path = "[id]"): string => `/events/${path}`,
```
We should talk about the pros and cons of each approach!

**Comment by matthewbrown77** [comment]
The changes in #83 are pretty straightforward and wouldn't be too difficult to incorporate into this task. One point of discussion is the pages object in config.ts. In my opinion, changing pages.events to be a function to handle both pages seems needlessly complex. I think it's much easier to just have 2 entries, 1 for viewing all events and 1 for specific events.

**Comment by PC98** [comment]
Sounds good to me!

**Comment by matthewbrown77** [comment]
I'm unable to get Next to properly generate the static paths when building the project. I decided to investigate further and run into the following error for each valid event id.

![date_error](https://user-images.githubusercontent.com/45107667/93840636-11444180-fc5f-11ea-8d21-a049b25d880a.png)

I found [this thread](https://github.com/vercel/next.js/discussions/11498) discussing the issue on the Next.js repository.

**Comment by matthewbrown77** [comment]
I was able to verify that `getStaticProps` works properly by temporarily modifying my query to only return the event name, so I think it must be an issue with my `getStaticPaths` implementation (though the previous error is still certainly frustrating when testing).

**Comment by PC98** [comment]
Okay, let me look into this and get back to you. Based on the discussion you linked, we will probably have to cast Date to a String type (but I wanna avoid using `.map()` so I will see if there is a better way, maybe something like SchemaType getters: http://thecodebarbarian.com/whats-new-in-mongoose-54-global-schematype-configuration.html#schematype-getters)

**Comment by PC98** [comment]
@matthewbrown77 A few solutions I thought of, which doesn't involve `.map()`ing through all the documents:
1. Add getters to Event schema's startDate and endDate:
```javascript
const eventSchema = new Schema(
  {
    // stuff
    startDate: {
      type: Date,
      default: Date.now,
      get: d => d.toString()
    },
    endDate: {
      type: Date,
      default: Date.now,
      get: d => d.toString()
    },
    //  stuff
  },
  { toObject: { getters: true }, toJSON: { getters: true } }
);
```
2. If you end up taking this approach, please modify all functions in `server/actions/events.ts` to not use `.lean()`, since Mongoose getters don't work with `.lean()`
3. You should also modify our Event type definition in `utils/types.ts` so that `startDate` and `endDate` are of type `string`, since after adding this Mongoose getter, the front-end code will always receive a `string` for  `startDate` and `endDate`.

An alternative approach would be to modify `startDate` and `endDate` in our Event schema to be of type `String` instead of `Date`. Then, you wouldn't have to add getters and we can still use `.lean()`. However, you will have to write a migration script for this change, and still do step (3) from above.

**Comment by matthewbrown77** [comment]
I'm leaning towards the first approach here. It does mean we have to remove uses of .lean(), but I think it saves us a lot of excessive complications for the existing (and future) event actions when we need to calculate something using the date fields.
