### ISSUE TITLE
[VMS] Possibly modify certain Events server actions to not return all event object fields

### ISSUE THREAD

**Issue by PC98** [GTBitsOfGood/gen-soln#160]
* Currently, we have `getUpcomingEvents()` and `getNearestEvents()` server actions. 
* These methods return all fields for matching Event objects. However, we should discuss if this is really necessary since the data from these methods will just be used to render an event card on the front-end.
* The event card only requires the following fields:
    * `startDate` and `endDate`
    * `name`
    * `image`
    * `address`
    * Nonprofit name.
* Here is what I propose: 
- [x] Let's rename these methods to something like `getUpcomingEventsCardData`and `getNearestEventsCardData`
- [x] Modify the query in `find` to drop the fields we don't need. To reduce code duplication, we can create an object, `const eventFieldsToDrop = { maxVolunteers: 0, about: 0 /* etc. */ }` and re-use it in all server actions that return data for event cards.
- [x] Modify the server actions to use [populate](https://mongoosejs.com/docs/populate.html), more particulary: https://mongoosejs.com/docs/populate.html#field-selection to get the Nonprofit name.
- [x] Now, the server actions will no longer be returning `EventType` data, so we will have to modify/create a new type in `utils/types`. Message me when you are working on this step.

**Comment by Fattimo** [comment]
![image](https://user-images.githubusercontent.com/57023314/93729141-3e2a2300-fb91-11ea-8639-47943863dc31.png)

With the modification of the query in find(), instead of dropping unwanted fields, why not prune the desired fields? From Mongoose find() documentation, reflected in line 13 of screenshot above

![image](https://user-images.githubusercontent.com/57023314/93729191-729ddf00-fb91-11ea-9ccd-9664778d1347.png)

**Comment by PC98** [comment]
Sure, that works too! I wasn't aware of this feature haha.
I guess using prune makes sense if your query is selecting _a few fields_ and dropping _several other fields_. Using the drop syntax makes sense if the query is selecting _several fields_ but dropping _a few_ of them.
