### ISSUE TITLE
Build sign-up/login page UI

### ISSUE THREAD

**Issue by rithikgavvala** [GTBitsOfGood/gen-soln#171]
https://www.figma.com/file/HMEsyyl6EGJ4hMaGBNtQNe/Donor-and-Volunteer-Experience-%2F-Fall20?node-id=0%3A1

Using the Figma create the sign-up page in the core components folder. Use the Horizon button for the sign-up.

Storybook could be useful in terms of designing the components in isolation.

https://storybook.js.org/docs/react/get-started/introduction

The docs for storybook should help you get started with developing using the UI.

`yarn run storybook
`
When developing the component create a folder in `components/core `and have the` stories.tsx` file and the normal component file in the same folder.

Utilize the auth0 package to bootstrap the UI for the login page. Here is the link for the documentation: https://github.com/auth0/auth0-react

**Comment by kw143** [comment]
Horizon Button will be added with #107.
