### ISSUE TITLE
Create the Google Places Autocomplete component

### ISSUE THREAD

**Issue by KoolCards** [GTBitsOfGood/gen-soln#200]
- [ ] Create a new autocomplete component (in components/donation/form). Essentially, the component code should be [this](https://material-ui.com/components/autocomplete/#GoogleMaps.tsx), but cleaned up a little more (i.e. make it full width and make the google maps api key a value in config.ts). Message me when you need the API key.
- [ ] Have this component accept a function called setAddress in the props and call this function on an address change with the new address (newInputValue in onInputChange) as a parameter. This will allow the parent component to keep track of the address state.

**Comment by PC98** [comment]
As an FYI, we have created a similar component for the Events page. Will your auto-complete be restricted to searching for US cities, or does DMS need something more granular (like street address autocomplete)?
