### ISSUE TITLE
[VMS] Implement "Upcoming Volunteer Events" list

### ISSUE THREAD

**Issue by PC98** [GTBitsOfGood/gen-soln#212]
* Modify the `EventsList` component **(note this is just a suggestion, feel free to think of your own ways to do this task!):** 
  - [x] It should take an object, `paginatedEventCardsData` of type `PaginatedEventCards` as props along with a function, something like `getMoreEvents`. `getMoreEvents` will take an integer, `newPage`as input and return an object of type `PaginatedEventCards`.
  - [x] Chage the `events` `useState` to be of type `EventCardData` (you can get this from `utils/types.ts`) and set the inital value to `paginatedEventCardsData.eventCards`.
  - [x] Create a new `useRef`, `pageRef` - set it's initial value to `paginatedEventCardsData.page`.
  - [x] Modify this line: `const [newEvents, hasMore] = await getEvents(fetchNum);` to: `const { newEvents : eventCards, newPage : page, isLastPage}  = await getMoreEvents(pageRef.current + 1)`. 
  - [x] Set `pageRef.current` to `newPage.`
  - [x] You will have to modify some other existing code to use `isLastPage` instead of `hasMore` and the `EventCardLarge` components will have to be rendered using the `EventCardData` type, instead of the `EventDisplayInfo` type created in this file. 
  - [ ] **Bonus points** if you can refactor `EventCardLarge`'s prop types to directly work with `EventCardData` instead of `headerText`, `bodyText`, etc.). Though let's talk to Miguel about this if he thinks this is a good idea. 
- [x] Then, make a component, something like `EventsPageMainContent`. This component will be rendered in `EventsPage.tsx` and for now, it should accept an object of type `DatePaginatedEventCards` as props (this was added to `EventsPage.tsx` as part of #211).
- [x] `EventsPageMainContent` should render the title text - "Upcoming Volunteer Events" and an `EventsList` component. Think about what props you want to pass to `EventsList`, particularly the `getMoreEvents` function. As a hint, `getMoreEvents` will use the fetch request added as part of #210. The input to the fetch request - `date` and `totalCount` it can get from its own props but the new `page` value be passed by `EventsList`.
- [ ] As an experiment, try adjusting the `CARDS_PER_PAGE` value defined in `server/events.ts` to see if that leads to a better UI overall.

**Comment by matthewbrown77** [comment]
@migueldlr What is your opinion on refactoring `EventCardLarge` to work directly with the `EventCardData` type instead of `headerText`, `bodyText`, etc. I'm assuming your reasoning for doing so has to do with the use of `clsx`? I'm not too familiar with this area so if you could explain your reasoning that would be very helpful.

**Comment by matthewbrown77** [comment]
@PC98 Even if we did refactor `EventCardLarge` we still need to handle the `imagePath` for the card. It's a little early to add that field to `EventCardData` in my opinion and it would require more work than just leaving the EventDisplayInfo type in use. We could modify it a bit to use the EventCardData properties and make it as easy as possible to remove it when the time comes.

**Comment by matthewbrown77** [comment]
@PC98 nvm I think I found a solution.

**Comment by matthewbrown77** [comment]
We will also need to add some additional logic to return the date string in our desired format since we are now working with the actual event objects in the database instead of dummy data.

**Comment by PC98** [comment]
Yep, `EventCardData` supports the `image` field that we could just use. 

> We will also need to add some additional logic to return the date string in our desired format since we are now working with the actual event objects in the database instead of dummy data.

For this, I think the front-end should handle formatting the startDate/endDate/duration and display the UI accordingly. But this task might be getting too long then. Perhaps, for now, you can just use `duration` in the card UI and I will make another task.

**Comment by migueldlr** [comment]
I know this is already closed, but I'm super okay with `EventCardLarge` taking in different props. I wrote it to be generalizable, but if there's no other significant usecase, then having it take in an `EventCardData` object with specific descriptions of the data is better.

**Comment by matthewbrown77** [comment]
In that case, we can open a separate issue or have one of the later frontend tasks incorporate it. Up to @PC98

**Comment by PC98** [comment]
Yep will make a task for this soon
