### ISSUE TITLE
[VMS] Implement the "Volunteer Events Near You" list

### ISSUE THREAD

**Issue by PC98** [GTBitsOfGood/gen-soln#242]
* For inspiration, look at how `EventsPageMainContent` renders the "Upcoming Volunteer Events" list.
* You will have to use HTML 5's Geocoding API to get the user's latitude and longitude information (potentially in a `useEffect` hook) and then make a call to `getNearestEventsCardData` via the request added as part of #213.
* The initial value for `isLastPage` can be false, `page` will be 0 and `totalCount` will be whatever invalid value is considered in #241.
* If a user refuses to share their location, or if the backend doesn't return any events near their location, we should not render this list component at all.

**Comment by matthewbrown77** [comment]
@PC98 Is there a better way to address conditional rendering rather than just having to check each prop field? For example, with just `upcomingEventsFirstPageData` and `nearestEventsFirstPageData`, we need to have 3 conditional renders checking each possible combination, which leads to a lot of duplicated code.

**Comment by matthewbrown77** [comment]
Actually, I think we could just move the conditional render into the `MainContent` component instead of `EventsPage`, which is where it currently is.

**Comment by PC98** [comment]
So actually when I said:

>  if the backend doesn't return any events near their location, we should not render this list component at all.

I meant that `EventsPageMainContent` should call the request added as part of #213 after it renders. Once we have the result from the request, it should render a`EventsPageEventList` component corresponding to the nearest events if the server returned a non-empty array.

I believe you are talking about the `props.upcomingEventsFirstPageData &&` check in `EventsPage.tsx`. I don't think you will have to make any changes to that as part of this issue.
Though I agree with the fact that checking `props.upcomingEventsFirstPageData` to determine if `EventsPageMainContent` should be rendered hides the fact that `EventsPageMainContent` is actually responsible for rendering other lists of data as well. I can put out a PR to make this more explicit.

**Comment by matthewbrown77** [comment]
@PC98 GET requests are still broken on the `develop` branch. If you visit our [vercel hosted build](bog-gen-soln.vercel.app) and navigate to `/events`, you can see that the initial upcoming events are never loaded, and that adding and then removing a filter sends a request that returns a 404.
![404](https://user-images.githubusercontent.com/45107667/95480929-73d55700-095a-11eb-9999-a0800bb31b4f.png)

**Comment by PC98** [comment]
Thanks for flagging, I will look into this

**Comment by matthewbrown77** [comment]
@PC98 I could use some help with the data fetching. Here is my current `useEffect` hook to fetch the nearest events:
```
let nearestEventsFirstPageData = null;

  useEffect(() => {
    if (navigator.geolocation) {
      navigator.geolocation.getCurrentPosition(position => {
        nearestEventsFirstPageData = getNearestEvents({
          page: 0,
          lat: position.coords.latitude,
          long: position.coords.longitude,
          totalCount: -1,
          isLastPage: false
        });
      });
    }
  }, []);
```
We are forced to use the `useEffect` hook here to ensure that the call to the geolocation API runs in the browser and not using SSR. I can see that the request is sent and returns an array of events. However, the value of `nearestEventsFirstPageData` is never changed. I assume it's because we aren't awaiting the response of `getNearestEvents`, but I'm not sure how to do that in a callback. Trying to set it using `.then()` chaining didn't work either. Unfortunately, I don't believe the geolocation API supports async / await.

**Comment by PC98** [comment]
I ran `yarn lint` on your code and this might be helpful:
```bash
Assignments to the 'nearestEventsFirstPageData' variable from inside React Hook useEffect will be lost after each render. To preserve the value over time, store it in a useRef Hook and keep the mutable value in the '.current' property. Otherwise, you can move this variable directly inside useEffect  react-hooks/exhaustive-deps
```
As a general rule of thumb, try running `yarn lint` when your React code isn't behaving as you expect it to 🙂

**Comment by matthewbrown77** [comment]
The problem with `useRef` is the type difference. Using a reference of type `LocationPaginatedEventCards` doesn’t work since `getNearestEvents` returns a promise and we shouldn’t be passing a promise as a prop.

**Comment by PC98** [comment]
Here is what I would recommend:
1. Let's make a hook to get the user's latitude and longitude coordinates and store it as state, **for inspiration see: https://itnext.io/creating-react-useposition-hook-for-getting-browsers-geolocation-2f27fc1d96de**.
2. Have a **seperate `useEffect` hook** whose dependencies are the latitude and longitude. If latitude and longitude are non-null you can make a request to `getNearestEvents` to get the first page of data. Since `getNearestEvents` is an async function, you will have to await it. The result from calling `getNearestEvents` should be stored in a state variable (so you will have to create a `useState` of type `LocationPaginatedEventCards`) and passed as a prop to `EventsPageEventList`.
3. You will also have to write a `getMoreEvents` function.
