### ISSUE TITLE
[VMS] Modify `FocusVisibleOnly` to use `pointer` cursor

### ISSUE THREAD

**Issue by PC98** [GTBitsOfGood/gen-soln#287]
* We added an on-click function to event cards in #252, however, when a user hovers their mouse over the cards, the mouse doesn't change to a cursor to indicate that the card is clickable.
* Make relevant changes to `FocusVisibleOnly` to correct this behavior. After this, you should be able to remove the `cursor: "pointer"` style in `EventsPageFilterContainer` since that also uses `FocusVisibleOnly`.
* Make sure to test any UI that might be affected by this change.

**Comment by matthebrown** [comment]
![pointer](https://user-images.githubusercontent.com/45107667/96045425-ee611380-0e3f-11eb-8793-1cb060501eb6.png)
