### ISSUE TITLE
[VMS] UI for EventsListing page header

### ISSUE THREAD

**Issue by PC98** [GTBitsOfGood/gen-soln#294]
* Look at the Figma design for the EventsListing page. You will be implementing just the UI portion (no back-end data integration) for the header which contains the text "380 Results" and the "Sort by" dropdown.
* You can create a new component that gets rendered by `EventsPageFiltered.tsx`. As an example, see how `EventsPageUnfiltered.tsx` renders `EventsPageMainContent`.
* You can use material-ui's `Select` component. For reference, `DonationPageHeaderSelect.tsx` uses it.
* You should use the `usePosition` hook. If the user selects "Closest to you", only then we should ask the user for their location. Though remember you can't use a hook conditionally. So you might have to either modify `usePosition` to control when the `useEffect` inside it gets called or think of some other clever way.
* If the user has denied sharing their location information with us, we should prevent them from selecting "Closest to you"/switch to the other option. In this case, we can show a toast to the user (https://material-ui.com/components/snackbars/#snackbar) or a simple JS window alert  to tell them they can't select the "Closest to you" options since we can't their location.
* For now, we **won't** update the URL through our dropdown.

**Comment by matthebrown** [comment]
@PC98 I am trying to figure out the best way to push the `<Select>` input box behind the Sort by and icon elements. I want the box to be invisible but still clickable. Currently working with `opacity: 0`. Setting `display: none` or `z-index` loses the interactivity. I considered just bringing the other elements over using negative margins but that seemed a bit hacky. Any suggestions?
![input_box](https://user-images.githubusercontent.com/45107667/96494149-f3450f00-1213-11eb-93ac-46d3d49cbab5.png)

**Comment by PC98** [comment]
Oh is this to avoid the bottom border of the input box? Can you just try using the `disableUnderline` prop, like `DonationPageHeaderSelect.tsx` does it.

**Comment by matthebrown** [comment]
This is to eliminate the space between the Sort by text and the menu arrow. The figma design for `EventListing` does not render the input box but still shows the drop-down when clicking. However, the on click does not trigger without the input box.

**Comment by PC98** [comment]
So I see two different things here.

1. For _reducing_ the space between "Sort by" and the menu arrow icon, which you can customize using the `IconComponent` prop of `Select`, you can set the `minWidth` of the `Select` component (or `FormControl` component if you are rendering `Select` inside of that) to a small value. Use either `className={yourClass}` or `classes={{ root: yourClass}}` to provide this style.
2. I still don't understand the input box UI thing. Is a `Select` component, with the default variant and `disableUnderline`, not enough to achieve the desired UI?

**Comment by PC98** [comment]
Another thing that might help with regards to point num 2: we want the default, already selected value to be "Most signed up". So perhaps the "Sort By" text can be rendered as an `InputLabel`

**Comment by matthebrown** [comment]
I decided to go with something a little different than the Figma, but I think it looks solid.
![new_sort](https://user-images.githubusercontent.com/45107667/96522109-b5121480-1240-11eb-8342-91c67df995ef.png)
Though I am still having trouble coming up with ways we can control when the `useEffect` activates in our position hook, since useEffect is a hook in itself.

**Comment by PC98** [comment]
UI looks good! You can probably modify the `usePosition` hook to take in a boolean parameter, something like `disabled` or whatever name you think is appropriate. If `disabled` is `true`, the `useEffect` in `usePosition` won't try to get the current position. You will have to edit the dependencies of the `useEffect` to include `disabled`.

Any component that uses `usePositoin` can pass an appropriate value for `disabled` and that value can be controlled by some state, like the selection of the "events near you" option from our dropdown.
