### ISSUE TITLE
[VMS] Implement the filtered events list

### ISSUE THREAD

**Issue by PC98** [GTBitsOfGood/gen-soln#333]
* Now that #296 is complete, it's time to implement the filtered events list rendered in `EventsPageFilteredContent` with actual, real data from the back-end.
* Keep in mind that the data for the first page of filtered events will come from `getServerSideProps` in `events/pages/index.tsx`. Subsequent data will be fetched using the `getFilteredEvents` request defined in `requests/events.ts`.
* You may have to make some changes to the infinite scroll component added as part of #291, like adding props to it. Feel free to look at   `CoreCardPaginationList.tsx` to get an idea of what you can do.

**Comment by matthebrown** [comment]
Just a heads up, `EventsPageFilteredContent` does not handle 0 results very gracefully. Probably want to make a future task to address this. Maybe we can render text indicating there are no results if the `totalCount` is 0
![no_results](https://user-images.githubusercontent.com/45107667/97388946-94386780-18af-11eb-9d42-a2ef1073e54f.png)

**Comment by matthebrown** [comment]
@PC98 I'm also running into a weird issue where the `EventsPageFilteredContent` is not re-rendering when the `filteredEvents` prop changes, even with the following code snippet:
```
const [events, setFilteredEvents] = useState(filteredEvents);

  useEffect(() => {
    setFilteredEvents(filteredEvents);
  }, [filteredEvents]);
```
I can see the state updating in the browser console, but the component fails to update.

**Comment by PC98** [comment]
I will make a task for this weekend, thanks for flagging!

Hmm it's hard to say without looking at your full code. Perhaps the component is updating, but the `filteredEvents` data itself is not (based on the snippet at least)?

**Comment by matthebrown** [comment]
I was able to get the events to re-render properly by moving which component the `useEffect` ran in. Now I'm thinking about approaches for passing the lat and long values to the `InfiniteScroll` component. We need to keep the `usePosition` logic in the header, so I'm looking for a way to lift the `lat` and `long` values out of the header component so it can be passed to the `InfiniteScroll`.

**Comment by PC98** [comment]
Why doesn't the approach that we took for Events Near You list work? Like the way the code is divided between `EventsPageMainContent.tsx` and `EventsPageEventList.tsx` (which is just a wrapper around `CardPaginationList`).

**Comment by matthebrown** [comment]
Well, we only want to pass the user's location in the request if the user selects sort by "closest to you". Right now these components are rendered in parallel inside `EventsPageFilteredContent`.
```
      <EventsPageFilteredHeader resultsLength={filteredEvents.totalCount} />
      <EventsPageInfiniteScroll filteredEvents={filteredEvents} />
```
 We need a way for the header to signal the `InfiniteScroll` that the user has shared their location and pass the position along (it seems wrong to duplicate the `usePosition` hook in components next to each other.

**Comment by PC98** [comment]
Yes, to share data between sibling components, you will have to lift the state up to their parent component which would be `EventsPageFilteredContent.tsx` in this case.

**Comment by matthebrown** [comment]
@PC98 I'd love to meet with you later this week to put the finishing touches on this task. I was having trouble lifting the state up when I was working last week. However, my power has been out since last Thursday so it's been difficult to continue work.

**Comment by PC98** [comment]
Sure no worries. We can do tomorrow after our team meeting?

**Comment by matthebrown** [comment]
Yeah that works for me

**Comment by matthebrown** [comment]
Recapping the main points and suggestions on how to finish this task:

- Pass the initial sort state through props so it can be controlled by `FilteredContent`
- Add a second `useEffect` for the position hook to avoid passing `undefined`
- Import `sortOptions` and `OptionValue` from the new `index.ts` file
- Pass data fetching functions to `InfiniteScroll` to promote re-use
- Pass the `setSortCallback` instead of the state function

@PC98 If I missed anything feel free to add it here!
