### ISSUE TITLE
[DMS] Remove nonprofit background image

### ISSUE THREAD

**Issue by KoolCards** [GTBitsOfGood/gen-soln#348]
Nonprofits won't be able to upload their own background image, so we need to remove the backgroundImage attribute from our website.

- [ ] Create a migrations script to remove the background field from all the nonprofits in our db.
- [x] Remove the background field from the nonprofit type in utils, and the nonprofit schema in server/models.
- [x] Refactor the create nonprofit action, DonationPageLayout (i.e. remove StyleProps, backgroundImage, backgroundSize, backgroundRepeat, backgroundPosition from the styles...), and refactor the DonatePage
- [x] Add a backgroundColor field in the DonationPageLayout style with a color of "#FFFAF1" (off-white)

**Comment by PC98** [comment]
@KoolCards Will the non-profit profile page use the same background image for all non-profits?

**Comment by KoolCards** [comment]
yea the plan is to use the same background image for all nonprofits.
