### ISSUE TITLE
[DMS] Regenerate donate page if the nonprofit id doesn't exist

### ISSUE THREAD

**Issue by KoolCards** [GTBitsOfGood/gen-soln#83]
Currently, the donate page (`pages/donate/[id].tsx`) uses `getStaticPaths` to retrieve a list of nonprofit names at build time (when the website is deployed), and `getStaticProps` to pre-render donate pages for the nonprofits at build time. However, this means we need to manually re-build the website each time a new nonprofit onboards onto our website to generate the new donate page. Instead, we should attempt to rebuild the donate page for any nonprofit id and throw an error if the nonprofit id doesn't exist.

- [x] Look at the Next.js [docs on data fetching](https://nextjs.org/docs/basic-features/data-fetching) to understand how `getStaticPaths()` and `getStaticProps()` work together. Read about the [`fallback` property](https://nextjs.org/docs/basic-features/data-fetching#fallback-true) in detail - you should modify how it is being used in `pages/donate/[id].tsx` to complete this task.
- [x] Notice that the `getStaticProps()` method calls `getNonprofitById(id)` to retrieve the non-profit object from our DB. When `fallback` was set to `false`, we could be certain that a non-profit with  id=`id` existed in our DB. But now, Next.js won't render a 404 page by default for non-existant `id`s. So you must enclose this code in a `try-catch` to catch [run-time exceptions thrown by `getNonprofitById(id)`](https://github.com/GTBitsOfGood/gen-soln/blob/develop/server/actions/nonprofit.ts#L51) for non-existant `id`s.
- [x] In your `try` block, you can keep returning `props: { nonprofit, items, selectedValue: id }`, however, you will have to decide what you want to return in the `catch` block. You could return an empty object, `props: {}`, as a suggestion.
- [x] Now, we will have to deal with type changes. Since `NonprofitDonationPage` is no longer guaranteed to receive a `nonprofit` object from `getStaticProps()` every time, it's **incorrect** to say:
```javascript
const NonprofitDonationPage: NextPage<React.ComponentProps<typeof DonationPage >>
```
So first, let's modify our `getStaticProps` function signature to:
```javascript
// eslint-disable-next-line @typescript-eslint/explicit-module-boundary-types
export const getStaticProps = async (context: GetStaticPropsContext) => {
```
And we will modify the `NonprofitDonationPage` declaration to:
```javascript
const NonprofitDonationPage: NextPage<InferGetStaticPropsType<typeof getStaticProps>> = props => {
```
This will tell TypeScript to infer the prop types of `NonprofitDonationPage` from the return type of `getStaticProps()`. You will have to import `GetStaticPropsContext`.
- [x] Now, in `NonprofitDonationPage`, we will have to [check if a fallback page](https://nextjs.org/docs/basic-features/data-fetching#fallback-pages) is being rendered. If it is, let's render `null` _(bonus points if you want to implement a loading component, like a simple header with loading text)._
- [x] If a fallback page isn't being rendered, check if the passed in `props` contain the `nonprofit` object and return the `DonationPage` component:
```javascript
if (props.nonprofit) {
  return <DonationPage {...props} />;
}
```
- [x] Below the above `if`, we will return 404 page UI. This UI is shown to users who visit `/donate/id` for a non-profit `id` that doesn't exist in our DB. You can use the `next/error` module for the 404 page UI, see: https://github.com/vercel/next.js/discussions/10960
- [x] Lastly, look into Next.js's incremental site generation: https://nextjs.org/docs/basic-features/data-fetching#incremental-static-regeneration feature. You will have to specify the `revalidate` property in `getStaticProps()` to avoid some weird UI bugs and behavior when using `fallback: true`; can you guess why?

**Comment by ML-Chen** [comment]
@PC98 I'm getting this error from IntelliJ, but compiling and running the page seems to work fine.
![image.png](https://images.zenhubusercontent.com/5d8168cc4def500001d12712/1531145e-aeed-453b-9550-907751c55786)
Should we worry about this?

**Comment by ML-Chen** [comment]
I'm also getting this error upon compilation now with yarn dev:
SerializableError: Error serializing `.items[3].value` returned from `getStaticProps` in "/donate/[id]".
Reason: `object` ("[object Object]") cannot be serialized as JSON. Please only return JSON serializable data types.
    at isSerializable (C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\lib\is-serializable-props.js:9:7)
    at C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\lib\is-serializable-props.js:7:503
    at Array.every (<anonymous>)
    at isSerializable (C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\lib\is-serializable-props.js:7:304)
    at C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\lib\is-serializable-props.js:7:774
    at Array.every (<anonymous>)
    at isSerializable (C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\lib\is-serializable-props.js:7:747)
    at C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\lib\is-serializable-props.js:7:503
    at Array.every (<anonymous>)
    at isSerializable (C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\lib\is-serializable-props.js:7:304)
    at isSerializableProps (C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\lib\is-serializable-props.js:9:219)
    at renderToHTML (C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\next-server\server\render.js:30:508)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\next-server\server\next-server.js:76:329
    at async __wrapper (C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\lib\coalesced-function.js:1:330)
    at async DevServer.renderToHTMLWithComponents (C:\Users\micha\Documents\Git\gen-soln\node_modules\next\dist\next-server\server\next-server.js:99:364)

**Comment by ML-Chen** [comment]
You can view my code at https://github.com/GTBitsOfGood/gen-soln/blob/michael/83-regen-donate/pages/donate/%5Bid%5D.tsx

**Comment by PC98** [comment]
Not sure about the second error yet, but for the first one just remove `GetStaticProps` from where you are declaring `getStaticProps` function. The `GetStaticProps` interferes with what `InferGetStaticPropsType` infers the return type to be.

**Comment by PC98** [comment]
@ML-Chen also as a suggestion, @matthewbrown77 found that the 404 page UI can be simplified to just `<ErrorPage statusCode={404} />;`, see: https://github.com/GTBitsOfGood/gen-soln/blob/15c11999e7b535ac0f5068e6661f81abff8df755/pages/events/%5Bid%5D.tsx#L24

**Comment by PC98** [comment]
I am able to compile using `yarn dev`, maybe the error was related to `GetStaticProps`, though not sure. Also, make sure that your local DB has all the migrations.

**Comment by ML-Chen** [comment]
Okay, that resolved the first error. The second error was because I tried making a new nonprofit in MongoDB, and that has an _id of ObjectID rather than string.

**Comment by PC98** [comment]
Yes, that's one of the reasons why we chose Nonprofits to have String IDs. I would recommend modifying the ID of the nonprofit document you have created -- our Mongoose schema expects Nonprofits to have String IDs.

If eventually down the road you have to return some data from the server that includes an ObjectID field, we can deal with that specific case then.

**Comment by ML-Chen** [comment]
Okay, I see. I'm not sure how to create a document with an ObjectID of string, so I'm not able to test whether it handles new nonprofits correctly.

**Comment by PC98** [comment]
If you are using MongoDB's `db` object, you can provide your own string `_id`, see how the `seed-nonprofits.ts` migration script does it.
If you are using Mongoose's methods to create a new Nonprofit, then you don't have to specify and `_id` yourself and Mongoose will default to using a randomly generated String.

**Comment by ML-Chen** [comment]
Ah nvm figured out how to do it in MongoDB Compass. It's just typing in a line for _id when you're creating a new document.
