### ISSUE TITLE
[VMS] Create a component for `/event` page layout

### ISSUE THREAD

**Issue by PC98** [GTBitsOfGood/gen-soln#92]
* Look at the designs for "EventsListing" in the "_Production" page of [this Figma doc](https://www.figma.com/file/HMEsyyl6EGJ4hMaGBNtQNe/Donor-and-Volunteer-Experience-Fall20?node-id=0%3A1).
* In this task, you will implement the layout component for this page, call it something like `components/events/EventsPageLayout.tsx`.  **Press "control+g" in Figma to see the grid layout.**
* Don't worry about implementing the top navigation bar - you just have to implement a page layout with two columns. The first column, which will be smaller in width, will eventually be used for "Filters" and the second column will eventually be used to display the list of events.
* **You will not implement the actual content of the two columns**. Instead, `EventsPageLayout.tsx` will take in a prop, called `leftRailComponent` or `sidebarComponent` of type `React.ReactNode` and `children` (this prop is available to use by default when using the type `React.FC`). `leftRailComponent`/`sidebarComponent` will be rendered in the first column and `children` will be rendered in the second column. **Have a look at `DonationPageLayout.tsx` for inspiration**.
* You can use `div`s to represent the two columns or [material-ui's layout components](https://material-ui.com/components/box/) (like `Box`, `Container`, `Grid`).
* Ensure that both columns are independently scrollable. Have a look at this website: https://careers.google.com/jobs/results/ Notice how the filters column `div` and the main content column `div` can be scrolled independently of one another.

**Comment by matthewbrown77** [comment]
@PC98 is it okay if I pick up this issue? I know it's another `good first issue`, but all the other issues appear to be blocked.

**Comment by PC98** [comment]
Yes sure :)

**Comment by matthewbrown77** [comment]
@PC98 What would the best way to test the layout be? I have a component that I believe works, but it's difficult to check without the sidebar component finished. It's basically two empty div's.

**Comment by PC98** [comment]
Yeah, the Core team is working on a way to test React components in isolation. For now, just to test it out, just render it as part of the `EventsPage` here: https://github.com/GTBitsOfGood/gen-soln/blob/develop/pages/events/index.tsx#L4
For your sidebar and children props, maybe pass in `div`s that fill their entire parent container; I think a style of `flex: 1` and different background color on the `div`s, to visually see things, will suffice. Though `flex: 1` by itself might not be enough to test the scrolling behavior, for that you can add a `height` style and give a large value.
