### ISSUE TITLE
[VMS] Component for event listing card

### ISSUE THREAD

**Issue by PC98** [GTBitsOfGood/gen-soln#97]
* In this task, you are going to create a component that implements the UI for an event card:![Screen Shot 2020-08-31 at 6.28.42 PM.png](https://images.zenhubusercontent.com/5a64edf34b5806bc2bc39e19/93a8a769-897e-4b6f-97f3-8cdddfd7fcdd)
* See Figma for detailed designs.
* This should be a "dumb" UI component, that is, it will receive all the content (like image, heading, body, meta text) that it has to render from its `props`. It itself won't hold any state.

**Comment by migueldlr** [comment]
@PC98 should the component be absolutely sized or fill its container? There are Figma examples for the component being [246x324](https://www.figma.com/file/HMEsyyl6EGJ4hMaGBNtQNe/Donor-and-Volunteer-Experience-%2F-Fall20?node-id=201%3A1685) and [266x237](https://www.figma.com/file/1VBjx7n3zFQMng4YUNX6iz/Horizon-%2F-Web?node-id=242%3A2045)

**Comment by PC98** [comment]
Thanks for bringing this up. I followed up with Jason and he said that the height should be static, 237px. He said the width can be a value in the 240-260px range depending on the grid layout of the page. Based on the layout component that the "EventsListing" page uses (see "_Production" page design in "Donor and Volunteer Experience", aka User Experience, Figma doc), the width should be 246px. Not sure how we want to handle this dynamic width though, since the Core team hasn't built layout components yet, should we take in width as a prop?

**Comment by PC98** [comment]
Also here are some specs related to max-lines and padding values:
<img width="415" alt="Screen Shot 2020-09-08 at 1 27 49 PM" src="https://user-images.githubusercontent.com/18293058/92510311-a3693600-f1d9-11ea-9777-bf815b3f9dc3.png">
